### ISSUE TITLE
Xojo 2019 r3.1 - Crash at launch 

### ISSUE THREAD

**Issue by Sebastien-Remy** [mikecotrone/CalendarTimeChooser#23] opened 2020-04-04 10:23 UTC
After downloading the project Xojo IDE crash when attempt to open CalendarTimeChooser.xojo_project

**Comment by npalardy** [comment] 2020-04-04 15:21
What OS are you on ?

**Comment by Sebastien-Remy** [comment] 2020-04-05 09:04
Thanks for reply, I use macOS

**Comment by npalardy** [comment] 2020-04-05 18:00
Does 2019r3.1 crash just when you start it without opening a project ?
I cannot reproduce a crash when opening this project on macOS 10.15.4

**Comment by mikecotrone** [comment] 2020-11-28 18:26
I can't reproduce this issue also on 2019r3.1 nor 20193.2. (Mac OS 10.15.7)

Closing for now.

**Closed by mikecotrone** 2020-11-28 18:26 UTC
